### ISSUE TITLE
upgrade handling in 0.3.0-beta.1

### ISSUE THREAD

**Issue by nursoda** [cloud-py-api/mediadc#90]
**Describe the bug**
Unexpected "unhandled exception" during app update.

**To Reproduce**
Do `occ app:update --all` on an NC25 instance with `beta` channel; yields
```
mediadc new version available: 0.3.0-beta.1
An unhandled exception has been thrown:
Error: Call to undefined method OCA\MediaDC\Service\UtilsService::checkForSettingsUpdates() in /<NC>/apps/mediadc/lib/Migration/AppUpdateStep.php:65
Stack trace:
#0 /<NC>/lib/private/Repair.php(127): OCA\MediaDC\Migration\AppUpdateStep->run()
#1 /<NC>/lib/private/legacy/OC_App.php(1064): OC\Repair->run()
#2 /<NC>/lib/private/legacy/OC_App.php(1001): OC_App::executeRepairSteps()
#3 /<NC>/lib/private/Installer.php(200): OC_App::updateApp()
#4 /<NC>/core/Command/App/Update.php(107): OC\Installer->updateAppstoreApp()
#5 /<NC>/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Update->execute()
#6 /<NC>/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#7 /<NC>/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#8 /<NC>/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#9 /<NC>/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#10 /<NC>/console.php(100): OC\Console\Application->run()
#11 /<NC>/occ(11): require_once('...')
#12 {main}Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
```

**Expected behavior**
No "unhandled exception".

**Additional context**
`php occ upgrade` resolves the issue.

**Comment by bigcat88** [comment]
Thanks for reporting, look like it is related to web part, **Andrey** will look later...

**Comment by bigcat88** [comment]
@nursoda  Was this bug present for 0.3.1?

**Comment by andrey18106** [comment]
As it is solved with `occ upgrade` command, for now closing. If there are any other problems, feel free to reopen this issue or create a new one.
